---
title: "IFN1"
author: "Julia GB"
date: "2023-05-03"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
### Load packages 

```{r echo=FALSE}
library(tibble)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readr)
library(readxl)
library(RColorBrewer)
library(wesanderson)
```

### Dataframe 

```{r data}
virus <- as.factor(c("rTOSV","rTOSV CBiT NSs","rTOSV NBiT NSs","rTOSV CTBiT NSs","rTOSV ∆NSs:NLuc"))
rel_IFN <- c(12,16,16,6,1)

tab_IFN <- tibble(virus,rel_IFN)
tab_IFN
```

### Visualize the data 

```{r graphique}
g3<-tab_IFN %>% mutate(virus= fct_relevel(virus, "rTOSV","rTOSV CBiT NSs","rTOSV NBiT NSs","rTOSV CTBiT NSs","rTOSV ∆NSs:NLuc")) %>% ggplot(aes(x=virus, y=rel_IFN, fill = virus)) +
  geom_col(aes(fill = virus), width = 0.5) +
  scale_y_continuous(breaks = seq(0,16, by = 2)) +
  scale_fill_manual(values = c("#87CEEB", "#4169E1","#00BFAB","#191970", "#00A86B")) +
  labs(x = "Virus", y = "Relative IFN") +
  theme_bw() +
  theme(axis.title.x = element_text(size = 16, face = "bold", vjust = 0.5, margin = margin(t = 10, r = 20, b = 0, l = 0)),
        axis.title.y = element_text(size = 16, face = "bold", vjust = 3, margin = margin(t = 0, r = 5, b = 0, l = 0)),
        axis.text.x = element_text(size = 15, face = 'bold'),
        axis.text.y = element_text(size = 15, face = 'bold'),
        title = element_text(size = 18, face = "bold"),
        strip.text = element_text(face = "bold", size = rel(1)),
        legend.position="none",
        legend.title= element_text(size = 16, face = "bold"),
        legend.spacing.x = unit(0.5, 'cm'),
        plot.margin = unit(c(1, 1, 1, 1), "cm"))
g3
```

